2104 feat/configure new user email
SEED-platform/seed pull request #2590
Opened 2021-02-16 21:50 UTC by Ryoken

#### Any background context you want to provide?

#### What's this PR do?
Adds options to the organization settings that customizes the email sent out when a user is invited.

#### How should this be manually tested?
See screenshots.

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/2104

#### Screenshots (if appropriate)
<img width="785" alt="Screen Shot 2021-02-16 at 2 37 50 PM" src="https://user-images.githubusercontent.com/564231/108125706-15d22200-7066-11eb-95c0-cc4292a3f4fe.png">

<img width="599" alt="Screen Shot 2021-02-16 at 2 38 25 PM" src="https://user-images.githubusercontent.com/564231/108125716-19fe3f80-7066-11eb-81d4-254d05fff54e.png">

<img width="470" alt="Screen Shot 2021-02-16 at 2 38 44 PM" src="https://user-images.githubusercontent.com/564231/108125731-1ff42080-7066-11eb-942a-fbec7bc025f6.png">

2021-02-16 21:58 UTC, RDmitchell commented
@Ryoken -- so this is for someone in an existing organization inviting another person to their organization.

What about at the "superuser" level, ie, when adding an organization to an instance, having the ability to customize the email content?

2021-02-16 22:50 UTC, Ryoken commented
> What about at the "superuser" level, ie, when adding an organization to an instance, having the ability to customize the email content?

Do you mean the email that reads like this?

> Hello {{ first_name }},
You are receiving this e-mail because you have been added to the '{{ new_org }}' organization by '{{ requested_by }}'. Please disregard this message if you are not expecting access to SEED.
You can view your new organization by logging into the SEED instance here:
{{ link }}
The SEED Team

If so, I can add settings to customize this email as well.

2021-02-18 18:45 UTC, Ryoken commented
Added customization options for the other email:

<img width="974" alt="Screen Shot 2021-02-18 at 10 24 07 AM" src="https://user-images.githubusercontent.com/564231/108405778-c105e700-71de-11eb-8522-ba36e05a2043.png">

2021-02-18 20:28 UTC, macintoshpie requested changes
This looks good!

- I think we are still waiting for feedback regarding translation requirements, I just left a comment on the issue
- the only way to invite an existing user to an org on the frontend is through the /admin page, which requires superuser privileges. Since this page isn't accessible by non-superusers, I think we should git rid of the changes for customizing this email (this would be all of the `user_added_*` fields)

2021-02-18 20:33 UTC, RDmitchell commented
@macintoshpie -- not sure I understand your 2nd bullet above, because the owner of an organiztion can invite others to become members of the org through the Organizations nav bar, Members link
![image](https://user-images.githubusercontent.com/6314950/108418048-8f444e80-71e5-11eb-93c7-0b84c5405b8e.png)

2021-02-18 20:53 UTC, macintoshpie commented
> @macintoshpie -- not sure I understand your 2nd bullet above, because the owner of an organiztion can invite others to become members of the org through the Organizations nav bar, Members link

@RDmitchell That link you reference treats it as if the email you provide doesn't already have an account on SEED (even if the email you provide is already linked to an existing SEED user).

There's another flow, from the admin page, where you can add _existing_ SEED users to another org, which sends a different email (the one that Ryo mentions here: https://github.com/SEED-platform/seed/pull/2590#issuecomment-781557843). My belief is that this latter one does not need to be customizable b/c of its inaccessibility to non-superusers.

2021-02-18 21:08 UTC, RDmitchell commented
@macintoshpie -- right, the email coming from the superuser admin world doesn't need to be customized. It can stay as is.

2021-02-18 22:46 UTC, Ryoken commented on seed/views/v3/organizations.py
> +        new_user_email_content = posted_org.get('new_user_email_content')
This will now be appended if it's not found in the body.  Good idea!

2021-02-19 01:00 UTC, macintoshpie approved these changes
Sliiick, very cool feature ⚡

2021-02-19 17:15 UTC, merged