feat(models): add BSyncr sample data example
SEED-platform/seed pull request #2703
Opened 2021-06-02 18:12 UTC by laurenliz22

#### Any background context you want to provide?
This update now includes the ability to use BSyncr analysis one of the sample data records.

#### What's this PR do?
This update now includes the ability to use BSyncr analysis for pm_parent_property_id = 5766973.  To make this work the record needed to have longitude/latitude and meter data.

#### How should this be manually tested?
Test that the record is able to produce BSyncr analysis in SEED's Platform

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/projects/14#card-58380230

#### Screenshots (if appropriate)

2021-06-02 19:01 UTC, macintoshpie requested changes
One comment about a missing file. Also maybe we could update the modal to indicate you can run a BSyncr analysis on the property?
![Screen Shot 2021-06-02 at 12 58 03 PM](https://user-images.githubusercontent.com/18518728/120537442-8a756600-c3a2-11eb-919f-d1cab4d7e780.png)

Once the file get's added I can do a full test with BSyncr

2021-06-02 19:29 UTC, laurenliz22 commented on seed/views/v3/organizations.py
> +        filename = 'PM Meter Data 12.xlsx'
@macintoshpie forgot we changed that, should be added now.

2021-06-02 20:41 UTC, macintoshpie reviewed
Tested locally with BSyncr and it ran successfully 👍 

Could you add the notes to the Modal about being able to run BSyncr analysis on that property? Once that's done this is ready to merge

2021-06-08 21:11 UTC, laurenliz22 commented
@updated Modal about being able to run BSyncr analysis on property

2021-06-10 15:48 UTC, macintoshpie approved these changes
Nice 💥

2021-06-15 17:09 UTC, macintoshpie commented
@laurenliz22 were you going to add anything else to this PR or can I merge it?

2021-06-15 17:47 UTC, laurenliz22 commented
> @laurenliz22 were you going to add anything else to this PR or can I merge it?

@macintoshpie this can be merged, nothing more to add - thank you!

2021-06-15 22:00 UTC, merged