build: update to django 3.0
SEED-platform/seed pull request #2736
Opened 2021-07-12 15:58 UTC by macintoshpie

#### Any background context you want to provide?

#### What's this PR do?
- use xlrd to check for empty workbook instead of pandas (removing pandas from SEED due to slow build time on alpine)

#### How should this be manually tested?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

2021-08-03 15:24 UTC, macintoshpie commented on requirements/base.txt
> +django==3.0.14
party time

2021-08-03 15:24 UTC, macintoshpie commented on requirements/base.txt
> +djangorestframework==3.12.2
🐞

2021-09-14 22:26 UTC, macintoshpie commented on requirements/base.txt
> +-e git+https://github.com/macintoshpie/jwt-oauth2.git@f2db7e16803969f6121129a7b2fa04d09ec5f5e9#egg=jwt-oauth2
🍴

2021-09-14 23:51 UTC, macintoshpie commented on requirements/base.txt
> +-e git+https://github.com/macintoshpie/jwt-oauth2.git@f2db7e16803969f6121129a7b2fa04d09ec5f5e9#egg=jwt-oauth2
@nllong can you fork my edits to this repo into the SEED org so yall can maintain it?
https://github.com/macintoshpie/jwt-oauth2

2021-09-20 21:11 UTC, Ryoken requested changes
This looks good once that repo is updated!

2021-09-21 15:25 UTC, macintoshpie commented on requirements/base.txt
> +-e git+https://github.com/SEED-platform/jwt-oauth2.git@f2db7e16803969f6121129a7b2fa04d09ec5f5e9#egg=jwt-oauth2
Now seed owns the jwt fork

2021-09-21 15:25 UTC, macintoshpie commented
Merging -- coveralls is failing to accept our push (though all tests passed)

2021-09-21 15:25 UTC, merged