2739 feat/add eui analysis
SEED-platform/seed pull request #2825
Opened 2021-08-19 18:04 UTC by Ryoken

#### Any background context you want to provide?

#### What's this PR do?
Adds a new analysis for EUI

#### How should this be manually tested?
Select one or more properties and run an analysis, then select "EUI".   For it to work, you need 12 months of consecutive electricity meter readings on the property.

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/2739

#### Screenshots (if appropriate)

2021-08-20 16:28 UTC, macintoshpie requested changes
This is awesome, great work on the consecutive meter stuff.

One issue I had though was the case where all properties are invalid. No analysis property views are created, so when viewing the analysis you don't know exactly why the properties were "bad"
![Screen Shot 2021-08-20 at 10 17 32 AM](https://user-images.githubusercontent.com/18518728/130264448-87b79293-fa7d-43f4-a4ec-368d36c22ae7.png)

Could you tweak the flow so that these analysis property views are still created and the messages get linked directly to them?

2021-08-20 16:28 UTC, macintoshpie commented on seed/tests/test_analysis_pipelines.py
> +class TestEuiPipeline(TestCase):
🙌  Thank you for adding these!

2021-08-20 16:28 UTC, macintoshpie commented on seed/analysis_pipelines/eui.py
> +}
😎  🔥

2021-08-20 16:28 UTC, macintoshpie commented on seed/analysis_pipelines/eui.py
> +                user_message=EUI_ANALYSIS_MESSAGES.ERROR_NO_VALID_PROPERTIES,
```suggestion
                user_message=EUI_ANALYSIS_MESSAGES[ERROR_NO_VALID_PROPERTIES],
```

2021-08-24 17:52 UTC, macintoshpie commented
> One issue I had though was the case where all properties are invalid. No analysis property views are created, so when viewing the analysis you don't know exactly why the properties were "bad"

On second thought let's just hold off on changing this too much. We should have a design discussion about how to document analyses and failure cases

2021-08-24 21:32 UTC, Ryoken commented on seed/analysis_pipelines/eui.py
> +                user_message=EUI_ANALYSIS_MESSAGES.ERROR_NO_VALID_PROPERTIES,
oops, good catch!

2021-08-24 22:02 UTC, macintoshpie approved these changes
🔥 🔥 🔥

2021-08-24 22:07 UTC, merged