Remove warnings from tests
SEED-platform/seed pull request #3077
Opened 2022-01-07 17:28 UTC by haneslinger

#### Any background context you want to provide?
✨ I recommend reviewing this PR one commit at a time ✨ 
It's big but each PR does _one_ thing. 

💥 There's still alot of errors. 😿 Explained in the ticket #3062 💥 

#### What's this PR do?
This  PR removes many of the warnings that appear when running the tests. 

#### How should this be manually tested?
To test, run 
```
python -Wd manage.py test 
```
#### What are the relevant tickets?
#3062 documents this PR commit by commit, and explains the remaining errors

#### Screenshots (if appropriate)

2022-01-10 16:13 UTC, macintoshpie requested changes
Lookin good! Just a few comments/questions

2022-01-10 16:24 UTC, macintoshpie commented
One more thing, it looks like we need to update our project settings for postoffice for this version so that Celery is enabled: https://github.com/ui/django-post_office/tree/v3.6.0#integration-with-celery

Specifically:
in common.py
```
POST_OFFICE = {
    'BACKENDS': {
        'default': 'smtp.EmailBackend',
        'post_office_backend': 'django.core.mail.backends.console.EmailBackend',
    },
    'CELERY_ENABLED': True,
}
```

in docker.py
```
POST_OFFICE = {
    'BACKENDS': {
        'default': EMAIL_BACKEND,
        'post_office_backend': EMAIL_BACKEND,
    },
    'CELERY_ENABLED': True,
}
```

2022-01-10 16:59 UTC, haneslinger commented on requirements/base.txt
> +-e git+https://github.com/SEED-platform/jwt-oauth2.git@9726367db36b332c84fb1288a7df32196509c06d#egg=jwt-oauth2
Pull request [here](https://github.com/macintoshpie/jwt-oauth2/pull/3). I can't request reviewers 🤔

2022-01-10 17:01 UTC, haneslinger commented on seed/data_importer/models.py
> +            self._local_file.close()
I agree.

2022-01-10 17:26 UTC, haneslinger commented on seed/lib/mcm/matchers.py
> +                jellyfish.jaro_winkler_distance(
You're right. Idk where I got `jaro_winkler_distance` from.

2022-01-10 17:46 UTC, haneslinger commented
| One more thing, it looks like we need to update our project settings for postoffice for this version so that Celery is enabled: https://github.com/ui/django-post_office/tree/v3.6.0#integration-with-celery

Great catch!

2022-01-10 18:10 UTC, haneslinger commented on seed/lib/mcm/matchers.py
> +                jellyfish.jaro_winkler_distance(
I figured it out, while the changelog totally  says `jaro_winkler` changed to `jaro_winkler_similarity` in 0.8.0, there's a [note in the doc](https://jamesturk.github.io/jellyfish/functions/#jaro-winkler-similarity) that says this change didn't happen til 0.8.1.

Additionally, the [git blame](https://github.com/jamesturk/jellyfish/commit/8f8546fa5d701d0bbc83f72b90ea7a780eb72c7c) show that there was a point in time where the function was named `jaro_winkler_distance`, but it appears to be attributed to v0.8.2 😵 

Long story short, `jaro_winkler_similarity` doesn't work on 0.8.0. I'm going to update it a few bug patches so the version we are using alines with the docs.

2022-01-10 18:26 UTC, haneslinger commented on requirements/test.txt
> +vcrpy==4.0.0
oh, idk, I've never worked with vcr before. @axelstudios, thoughts?

2022-01-10 19:24 UTC, macintoshpie commented on requirements/base.txt
> +-e git+https://github.com/SEED-platform/jwt-oauth2.git@9726367db36b332c84fb1288a7df32196509c06d#egg=jwt-oauth2
Oops, sorry I meant into SEED's fork

2022-01-11 23:09 UTC, haneslinger commented on requirements/test.txt
> +vcrpy==4.0.0
We've looked into it, vrc was sorta broken even before this PR. It's not to be fixed in this PR, it works here. [Here's the ticket](https://github.com/SEED-platform/seed/issues/3095)

2022-01-12 18:18 UTC, macintoshpie approved these changes
LGTM 👍  Looks like we are going to test/fix vcr in a separate issue

2022-01-12 18:49 UTC, merged