meter usage by month down to the second
SEED-platform/seed pull request #3215
Opened 2022-04-21 21:12 UTC by perryr16

#### Any background context you want to provide?
Sorts meter data by month using a per second meter reading

#### What's this PR do?

#### How should this be manually tested?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

2022-04-26 15:13 UTC, perryr16 commented
A new issue for "overlapping meter data error" should be generated

2022-04-26 20:57 UTC, Ryoken commented on seed/tests/test_property_views.py
> +    @skip('Overlapping data is not valid through ESPM. This test is no longer valid')
Nice, didn't know about @skip yet

2022-04-26 21:28 UTC, Ryoken approved these changes
Looks and works great!

2022-04-27 14:14 UTC, anchapin commented
I looked into how the energy data is being split between months and found differences between what SEED is doing, what ESPM does, and what makes sense to me. I used PM ID 3207429, electricity meter reading from 1/6/18 to 2/6/18 for the example. The spreadsheet and the table inserted below show the results of my comparison. Note that I'm not sure this matters too much unless users will be comparing the monthly values between SEED and PM.

Additionally, I included my suggested approach since if you refer to the "Day Counting" sheet of the "Comparison of Splitting Data_Chapin.xlsx" spreadsheet, you'll notice that the PM approach ends up double counting the start and end dates (i.e. the total number of days for a year period is greater than 365). However, this isn't necessarily a problem since you are just trying to figure out a way of splitting the data between two months. Therefore, my recommendation would be to revise the SEED code to match the ESPM approach.

[Comparison of Splitting Data_Chapin.xlsx](https://github.com/SEED-platform/seed/files/8572790/Comparison.of.Splitting.Data_Chapin.xlsx)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/achapin/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/achapin/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl63
	{border:.5pt solid windowtext;}
.xl64
	{mso-number-format:"mmm\\-yy";
	border:.5pt solid windowtext;}
.xl65
	{mso-number-format:"_\(* \#\,\#\#0\.00_\)\;_\(* \\\(\#\,\#\#0\.00\\\)\;_\(* \0022-\0022??_\)\;_\(\@_\)";
	border:.5pt solid windowtext;}
.xl66
	{mso-number-format:"_\(* \#\,\#\#0_\)\;_\(* \\\(\#\,\#\#0\\\)\;_\(* \0022-\0022??_\)\;_\(\@_\)";
	border:.5pt solid windowtext;}
-->
</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | SEED | Chapin | PM
-- | -- | -- | --
Total Days | 31 | 31 | 32
Jan-18 | 26 | 25.5 | 26
Feb-18 | 5 | 5.5 | 6
Energy Jan | 37,037.42 | 36,325.16 | 35,880
Energy Feb | 7,122.58 | 7,834.84 | 8,280



</body>

</html>

2022-04-27 14:18 UTC, anchapin requested changes
I just found the review changes section. Refer to my comments about matching the ESPM approach to splitting the data.

2022-04-27 17:27 UTC, anchapin approved these changes
After discussing with @perryr16, I agree that this pull request should be approved since it effectively splits the data into monthly portions. Additionally, I will open a new issue to reflect my comments on updating SEED to have the same approach as Energy Star's Portfolio Manager tool.

2022-04-27 17:30 UTC, merged