3795 edit delete scenarios measures
SEED-platform/seed pull request #3815
Opened 2023-02-01 18:05 UTC by perryr16

#### Any background context you want to provide?

#### What's this PR do?

#### How should this be manually tested?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

2023-02-01 21:27 UTC, nllong commented
Hey @perryr16  -- thanks for getting this in there. Just a quick heads up since you probably didn't know of the process update. We are now auto-generating the changelogs from the pull requests whereas before we were creating it from closed issues. So the pull requests title now becomes the change log entry. Can you update this title name to start with a verb and capitalized, e.g., Add ability to delete measures... or whatever.

2023-02-01 21:28 UTC, nllong requested changes

2023-02-01 21:58 UTC, perryr16 commented on seed/api/v3/urls.py
> +property_measures_router.register(r'property_measures', PropertyMeasureViewSet, basename='property-measures')
Can do. This feels related to how the `property` in URL `/properties/101` is actually a `property_view`

2023-02-02 15:26 UTC, nllong commented on seed/api/v3/urls.py
> +property_measures_router.register(r'property_measures', PropertyMeasureViewSet, basename='property-measures')
exactly. I just want the routes to be reflective of how a building analyst understands the world.

2023-02-03 15:17 UTC, anchapin requested changes
This is looking pretty good. However, I have two requests:

1. I expected that the "id" returned with "v3_properties_scenarios_measures_list" would be the id from the "propertymeasure" table in the database not the one from the "measure" table. This appears to be coming from the "PropertyMeasureSerializer" [here](https://github.com/SEED-platform/seed/blob/40ee2e609a7e4d94205b0c7afb6a08f6fb1b51ab/seed/serializers/measures.py#L21). This code was edited last by @nllong so can you chime in on whether this was done intentionally or not?
2. The data types listed in swagger for the "v3_properties_scenarios_measures_update" endpoint don't match what is actually expected. For example, "category_affected" is listed as data type of string but is actually expected to be an int.

2023-02-03 18:05 UTC, perryr16 commented
@anchapin regarding 
>The data types listed in swagger for the "v3_properties_scenarios_measures_update" endpoint don't match what is actually expected. For example, "category_affected" is listed as data type of string but is actually expected to be an int.

I agree. It's a bit confusing. However, these fields are enum fields that take an integer and return a string. I believe the desired pattern is to input `"category_affected": 1` and return `"category_affected": "Heating System"`. I can change the field to accept an integer and return an integer but that might contradict the intended functionality. 

thoughts?

2023-02-06 17:26 UTC, perryr16 commented
@anchapin, thanks for the feedback. I've manually changed the data types in the request body for the Scenario and Measure update endpoints.
![Screenshot 2023-02-06 at 10 23 36 AM](https://user-images.githubusercontent.com/58446472/217041620-1d131b9a-7bab-4927-af12-242d5085b81f.png)
![Screenshot 2023-02-06 at 10 23 22 AM](https://user-images.githubusercontent.com/58446472/217041624-79e2a821-2885-4144-b947-328547c57a9f.png)

2023-02-06 20:11 UTC, anchapin commented
> I expected that the "id" returned with "v3_properties_scenarios_measures_list" would be the id from the "propertymeasure" table in the database not the one from the "measure" table. This appears to be coming from the "PropertyMeasureSerializer" [here](https://github.com/SEED-platform/seed/blob/40ee2e609a7e4d94205b0c7afb6a08f6fb1b51ab/seed/serializers/measures.py#L21). This code was edited last by @nllong so can you chime in on whether this was done intentionally or not?

@nllong can you respond to this question regarding the "PropertyMeasureSerializer"? Let me know if you want to discuss it.

2023-03-07 18:45 UTC, nllong commented
Strange, I thought for sure that I responded to the `PropertyMeasureSerializer` question. Regardless, the `de9b4f8` commit above implemented the correct fix... it should have been the `propertymeasure_id`.

2023-03-07 18:48 UTC, nllong approved these changes
measure editing! Looks good.

2023-03-07 21:29 UTC, anchapin approved these changes

2023-03-19 22:50 UTC, axelstudios commented
@perryr16 I added some fixes:
- Fixed 500 errors when the input datatypes did not match the expected model types
- Fixed 500 error when using PUT with a nonexistent scenario
- Removed 3 fields from the scenario input model that always resulted in 500 errors: `measures`, `property_state`, and `reference_case`
- Removed unused pagination inputs on measures endpoints
- Fixed listing measures for a scenario, if the scenario exists with zero measures it now returns an empty array rather than a 404
- Fixed measure input model, `recommended` is a boolean rather than a string
- Updated schema generation to allow OpenAPI enum types and document the enum options
- Added enum validation to scenario/measure endpoints. Strings and ints are both accepted and validated
  - Before, this was resulting in 500 errors if invalid options were sent, like `false` or `0` or other invalid enum integers.  Subsequently, any endpoint that pulled in another model with an invalid integer would start returning 500 errors.
- Fixed Inventory Detail duplicate BuildingSync filetype errors (unrelated to this PR)

#### Potential issues that remain unfixed:
- The PUT requests actually behave like PATCH instead, merging partial input data with the existing record
- A measure can be update/deleted from a scenario, but can't be added

**Enum types**:
![2023-03-19_162500](https://user-images.githubusercontent.com/411466/226214602-7ef2c3c6-9194-4a42-914b-c2e20cb3efa4.png)

2023-03-19 22:51 UTC, axelstudios approved these changes

2023-03-20 00:10 UTC, merged

2023-03-20 14:07 UTC, perryr16 commented
@axelstudios Amazing, thank you for all that work