179d create_property endpoint
SEED-platform/seed pull request #4012
Opened 2023-04-27 21:47 UTC by kflemin

Create a new "Create property" endpoint which creates a property, propertystate, & propertyview via API.  

Needed for 179d web application.

2023-05-22 23:14 UTC, axelstudios requested changes
@kflemin I pushed up several fixes for unhandled errors, but there are TONS that remain:

There's no validation for the state object beyond the basic serializer - the user can pass in anything:
- If the state's `organization` and `organization_id` reference a different org than the one used for the query parameter it will accept it regardless, and the state will be inserted for the wrong org
- Should users be able to pass in an entire `extra_data` json object?  This seems like a vulnerability since they could completely exhaust the database storage in no time with massive json objects
- There are tons of state fields the user should _not_ be able to input:
  - `id`
  - `measures`
  - `scenarios`
  - `files`
  - `import_file_id`
  - `organization_id`
  - `data_state`
  - `merge_state`
  - `normalized_address`
  - `long_lat`
  - `centroid`
  - `bounding_box`
  - `hash_object`
  - `created`
  - `updated`
  - `import_file`
  - `organization`
  - and certainly more

2023-08-04 15:11 UTC, nllong commented on docs/source/translation.rst
> +2. Copy lokalise.yml.example to lokalise.yml. Update API token.
our lokalise instructions were out of date

2023-08-04 15:17 UTC, nllong commented on seed/tests/test_account_views.py
> +
if in your `local_untracked` you have set your own better and AT URLs, then this test fails locally. So let's just check to make sure that it matches a regex.

2023-08-04 15:19 UTC, nllong commented on seed/tests/test_portfoliomanager.py
> +        data = resp.json()
I replace these when I see them.

2023-08-04 15:48 UTC, nllong approved these changes
@axelstudios  -- this is ready for another review.

2023-08-04 15:50 UTC, nllong commented
> @kflemin I pushed up several fixes for unhandled errors, but there are TONS that remain:
> 
> There's no validation for the state object beyond the basic serializer (and I don't think we'd even want to use that serializer for validation since it requires 17 fields, many of which I wouldn't expect to be relevant like `organization_id` and `total_ghg_emissions_intensity`) - the user can pass in anything:
> 
> * If the state's `organization` and `organization_id` reference a different org than the one used for the query parameter it will accept it regardless, and the state will be inserted for the wrong org
> * Should users be able to pass in an entire `extra_data` json object?  This seems like a vulnerability since they could completely exhaust the database storage in no time with massive json objects
> * There are tons of state fields the user should _not_ be able to input:
>   
>   * `id`
>   * `measures`
>   * `scenarios`
>   * `files`
>   * `import_file_id`
>   * `organization_id`
>   * `data_state`
>   * `merge_state`
>   * `normalized_address`
>   * `long_lat`
>   * `centroid`
>   * `bounding_box`
>   * `hash_object`
>   * `created`
>   * `updated`
>   * `import_file`
>   * `organization`
>   * and certainly more

1. This should not be a problem. The org_id is validated on the endpoint.
2. We could enforce only columns that have been added to an org to be allowed in extra_data?
3. The Write Serializer protects all of the "Column.EXCLUDE_.*" objects.

2023-08-12 15:48 UTC, nllong commented on seed/lib/xml_mapping/mapper.py
> +        if isinstance(asset, dict):
This should never happen with the latest BAE code. @axelstudios  - you probably just needed to run `pip install -r requirements/local.txt`

2023-08-15 06:08 UTC, axelstudios approved these changes

2023-08-15 18:43 UTC, axelstudios commented
Here are the changes I've made:
- Removed broken `property_id` option
- Fixed extra_data columns to only ones that actually apply
- Changed `merge_state` from 0 to 1 (new)
- Added ValueError handling
- Small cleanup

2023-09-06 21:13 UTC, merged