Add public geojson endpoint
SEED-platform/seed pull request #4670
Opened 2024-05-14 19:24 UTC by perryr16

#### Any background context you want to provide?

#### What's this PR do?

#### How should this be manually tested?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

2024-05-24 15:15 UTC, nllong reviewed
Shouldn't this be "Returns a GeoJSON with the fields defined in the Organization Sharing selections"?

![image](https://github.com/SEED-platform/seed/assets/1907354/503950e5-88f8-40d8-b37a-cdf1dd305c64)


When clicking on the "Organization Sharing" link in the "Enable Public Endpoints" description, it returns this:

![image](https://github.com/SEED-platform/seed/assets/1907354/871daf20-1da5-4788-8e53-5af75850d754)

2024-05-24 15:17 UTC, nllong requested changes
see previous comment

2024-05-29 17:43 UTC, perryr16 commented
Updated help text
![Screenshot 2024-05-29 at 11 42 26 AM](https://github.com/SEED-platform/seed/assets/58446472/b27a6d1f-9273-4c5a-9c63-164ea8f0bbdd)

2024-06-28 23:13 UTC, kflemin approved these changes

2024-06-29 02:39 UTC, merged