Move show populated to backend
SEED-platform/seed pull request #4866
Opened 2024-10-24 00:50 UTC by haneslinger

#### Any background context you want to provide?

#### What's this PR do?

#### How should this be manually tested?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

2024-10-28 21:46 UTC, perryr16 commented on seed/static/seed/js/controllers/show_populated_columns_modal_controller.js
>        spinner_utility.show();
```suggestion
      spinner_utility.show();
      $uibModalInstance.close();
```
Might be nice to close the modal once refresh is initiated

2024-10-30 17:02 UTC, perryr16 approved these changes
🏆

2024-11-04 17:28 UTC, kflemin requested changes
this seems to work for me on the inventory list page, but I get this error on the inventory detail page and the modal hangs: 
![Screenshot 2024-11-04 at 10 24 23 AM](https://github.com/user-attachments/assets/fd65a7ba-a7a8-49a9-ae05-b60b87f1cd95)

2024-11-04 17:30 UTC, haneslinger commented
ah, I forgot about that page. let me at it

2024-11-05 00:03 UTC, kflemin approved these changes

2024-11-05 00:04 UTC, merged